name: Windows 10 RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive ngrok.zip

    - name: Auth Ngrok
      run: .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -value 1

    - name: Create User
      run: |
        net user runneradmin ${{ secrets.WINDOWS_USER_PASSWORD }} /add /expires:never
        net localgroup administrators runneradmin /add

    - name: Start Ngrok
      run: Start-Process Powershell -ArgumentList '-Noexit','-Command','.\ngrok\ngrok.exe tcp 3389'

    - name: Connect to RDP
      run: |
        cmd /c ping -t 127.0.0.1 >nul
